In [2]:
!ls

'ls'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [3]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: F603-5858

 C:\mypy 디렉터리

2017-11-14  오전 12:24    <DIR>          .
2017-11-14  오전 12:24    <DIR>          ..
2017-11-14  오전 12:24    <DIR>          .ipynb_checkpoints
2017-11-14  오전 12:23    <DIR>          Untitled Folder
2017-11-14  오전 12:24                72 Untitled.ipynb
               1개 파일                  72 바이트
               4개 디렉터리  120,821,288,960 바이트 남음


In [4]:
!ls

'ls'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [6]:
import os
os.rename('Untitled Folder','test1')

In [7]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: F603-5858

 C:\mypy 디렉터리

2017-11-14  오전 12:27    <DIR>          .
2017-11-14  오전 12:27    <DIR>          ..
2017-11-14  오전 12:24    <DIR>          .ipynb_checkpoints
2017-11-14  오전 12:23    <DIR>          test1
2017-11-14  오전 12:26             3,311 Untitled.ipynb
               1개 파일               3,311 바이트
               4개 디렉터리  120,805,126,144 바이트 남음


In [8]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

In [9]:
%macro

[]

In [10]:
!macro

'macro'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [2]:
import numpy as np
import scipy
import sklearn

In [4]:
np.__version__

'1.13.3'

In [5]:
sklearn.__version__

'0.19.1'

In [6]:
scipy.__version__

'1.0.0'

In [7]:
from sklearn import datasets
iris= datasets.load_iris()
print(iris.DESCR)
print(iris.target_names)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [11]:
x,y= iris.data, iris.target
print('Size of data:%s'% (x.shape, ))
print('Target value:%s'% np.unique(y))

Size of data:(150, 4)
Target value:[0 1 2]


In [14]:
print(x[0:10,:])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]


In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=1)
knn.fit(x,y)
predicted_value= knn.predict(sample)
print(iris.target_names[predicted_value])
print(knn.predict_proba(sample))

TypeError: float() argument must be a string or a number, not 'builtin_function_or_method'

In [13]:
knn= KNeighborsClassfier(n_neighbors=10, weights='distance')
knn.fit(x,y)
predicted_value= knn.predict(sample)
print(knn.predict_proba(sample))
print(iris.target_names[predicted_value])

NameError: name 'KNeighborsClassfier' is not defined

In [2]:
exec(open('D:/github/myPycharm/test').read())

PermissionError: [Errno 13] Permission denied: 'D:/github/myPycharm/test'

In [8]:
range(3,10)

range(3, 10)

In [2]:
1234567890123456789012345678901234567890

1234567890123456789012345678901234567890