#### 15 popular pkg
> __NumPy__, 
SciPy, 
Pandas, 
Matplotlib, 
Seaborn, 
Bokeh, 
Plotly, 
SciKit-Learn, 
Theano, 
TensorFlow, 
Keras, 
NLTK, 
Gensim, 
Scrapy, 
Statsmodels, 

#### [tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

In [2]:
import numpy as np

In [3]:
a= np.arange(15); a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a= np.arange(15).reshape(3,5); a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a= np.array([2,3,4]); a

array([2, 3, 4])

In [6]:
a.dtype

dtype('int32')

In [8]:
b= np.array([1.2, 3.5, 5.1]); b

array([ 1.2,  3.5,  5.1])

In [9]:
b.dtype

dtype('float64')

In [10]:
a= np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [12]:
a= np.array([1,2,3,4]); a

array([1, 2, 3, 4])