In [1]:
lt= [1,'s',['b','c']]
print(id(lt),type(lt))
print(id(lt[0]),type(lt[0]))
print(id(lt[1]),type(lt[1]))
print(id(lt[2]),type(lt[2]))

1681857139400 <class 'list'>
1500864736 <class 'int'>
1681676944920 <class 'str'>
1681857139208 <class 'list'>


In [18]:
import array
L= list(range(12))
A= array.array('b',L)
print(A)
print(A.typecode)
print(A.tolist())
print(A.buffer_info())


array('b', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
b
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
(1681843672000, 12)


In [23]:
import numpy as np
nda= np.array([1,2,3,4,5])
print(nda.shape)
print(nda.dtype)
print(nda.ndim)
print(nda.strides)
print(nda.data.tolist())


(5,)
int32
1
(4,)
[1, 2, 3, 4, 5]


In [28]:
import numpy as np
#integer array
i= np.array([1,4,2,5,3])
print(i)
print(i.dtype)

#float array
f= np.array([3.14,4,2,3])
print(f)
print(f.dtype)

#nested lists result in multi-dimensional arrays
mi= np.array([range(i,i+3) for i in [2,4,6]])
print(mi)

[1 4 2 5 3]
int32
[ 3.14  4.    2.    3.  ]
float64
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [32]:
#create a length 10 integer array filled with zeros
ze= np.zeros(10,dtype=int)
print(ze)
#create a 3x5 floating-point array filled with ones
one= np.ones((3,5),dtype= float)
print(one)
#create a 3x5 array filled with 3.14
fl= np.full((5,5),10)
print(fl)

[0 0 0 0 0 0 0 0 0 0]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [23]:
import numpy as np
#create a 3x3 identify matrix. eigen matrix?
ey= np.eye(3)
print(ey)

#create an uninitialized array of three integers
#the values will be whatever happens to already exist at that memory location
em= np.empty(6)
print(em)

m1= list(["gender","age","sb"])
m1= np.eye(3)
m1

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[  6.23042070e-307   1.42417221e-306   1.60219306e-306   9.79054228e-307
   1.69119330e-306   8.01097889e-307]


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

##  93

In [17]:
import numpy as np
#create an array filled with a linear sequence
#starting at 0, ending at 20, stepping by 2
#(this is similar to the built-in range() function)
ar= np.arange(1,88,10)
print(ar)

#create an array of five values evenly spaced between 0 and 1
ls= np.linspace(0,1,10)
print(ls)

[ 1 11 21 31 41 51 61 71 81]
[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


In [ ]:
import numpy as np
#create a 3x3 array of uniformly distributed
#random values between 0 and 1
rr= np.random.random((3,3))
print(rr)

#create a 3x3 array of normally distributed random values
#(mean, 표준deviation, (col,rows)) - deviation_일탈/편차. ex. +- 1
rn= np.random.normal(0,0.1,(3,3))
print(rn)

#create a 3x3 array of random intergers in the interval [0,10)
ri= np.random.randint(0,10,(3,3))
print(ri)

In [171]:
rni= abs(floor(np.random.normal(29.998,14.52649,(6,6))))
print(rni)

[[ 30.  41.  44.  27.  13.  34.]
 [ 25.  18.  43.  12.  27.  41.]
 [ 29.  45.  22.  36.  37.  25.]
 [ 29.  37.  22.  35.  29.  41.]
 [ 50.  38.  21.  11.   1.  24.]
 [ 36.  10.  23.  56.  35.  15.]]


In [176]:
z1= np.zeros((2,2),dtype='int16')
print(z1)
print(z1.dtype)

z2= np.ones((2,2),dtype=np.int16)
print(z2)
print(z2.dtype)

z3= np.ones(10,dtype=np.int16)
print(z3)
print(z3.dtype)

[[0 0]
 [0 0]]
int16
[[1 1]
 [1 1]]
int16
[1 1 1 1 1 1 1 1 1 1]
int16


In [180]:
int8 - 127   
int16 +- 3.2*10^4   
int32 +- 2.1*10^9   
nt64 +- 9.2*10^18   

uint8 uint16 uint32 uint 64 - 딱2배+1

float_ float16 float32 float64 complex_ complex64 complex128

SyntaxError: invalid syntax (<ipython-input-180-509b75a88881>, line 6)

In [187]:
import numpy as np
np.random.seed() #seed for reproducibility

x1= np.random.randint(10,size=6) #one-dimensional array
print(x1.flatten())
print("x1 차원:", x1.ndim)
print("x1 형태:", x1.shape)
print("x1 size:", x1.size)
print("x1 dtype:", x1.dtype)
print("원소당size itemsize: ", x1.itemsize," bytes")
print("객체전체size nbytes: ",x1.nbytes,"bytes")

[5 8 0 5 1 5]
x1 차원: 1
x1 형태: (6,)
x1 size: 6
x1 dtype: int32
원소당size itemsize:  4  bytes
객체전체size nbytes:  24 bytes


In [190]:
import numpy as np
np.random.seed(0)
x2= np.random.randint(10,size=(3,4)) #two diemnsional array

print(x2)
print(x2.flatten()) #행단위로 펴짐
print("x2 차원:", x2.ndim)
print("x2 형태:", x2.shape)
print("x2 size:", x2.size)
print("x2 dtype:", x2.dtype)
print("원소당size itemsize: ", x2.itemsize," bytes")
print("객체전체size nbytes: ",x2.nbytes,"bytes")

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[5 0 3 3 7 9 3 5 2 4 7 6]
x2 차원: 2
x2 형태: (3, 4)
x2 size: 12
x2 dtype: int32
원소당size itemsize:  4  bytes
객체전체size nbytes:  48 bytes


In [194]:
import numpy as np
np.random.seed(0)
x3= np.random.randint(10,size=(2,3,6))

print(x3)
print(x3.flatten()) #행단위로 펴짐
print("x3 차원:", x3.ndim)
print("x3 형태:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)
print("원소당size itemsize: ", x3.itemsize,"bytes")
print("객체전체size nbytes: ",x3.nbytes,"bytes")

[[[5 0 3 3 7 9]
  [3 5 2 4 7 6]
  [8 8 1 6 7 7]]

 [[8 1 5 9 8 9]
  [4 3 0 3 5 0]
  [2 3 8 1 3 3]]]
[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1 5 9 8 9 4 3 0 3 5 0 2 3 8 1 3 3]
x3 차원: 3
x3 형태: (2, 3, 6)
x3 size: 36
x3 dtype: int32
원소당size itemsize:  4 bytes
객체전체size nbytes:  144 bytes


In [197]:
import numpy as np
np.random.seed(0) #seed for reproducibility

x1= np.random.randint(6,size=6) #1차원배열
x2= np.random.randint(8,size=(3,2)) #2차원배열
x3= np.random.randint(12,size=(3,2,4)) #3차원배열
#첫 원소
print(x1[0])
print(x2[0])
print(x3[0])
#마지막 원소
print(x1[-1])
print(x2[-1])
print(x3[-1])

print(x3)


4
[7 1]
[[ 7  6  8  8]
 [10  1  6  7]]
3
[2 4]
[[3 0 3 5]
 [0 2 3 8]]
[[[ 7  6  8  8]
  [10  1  6  7]]

 [[ 7  8  1  5]
  [ 9  8  9  4]]

 [[ 3  0  3  5]
  [ 0  2  3  8]]]


In [206]:
import numpy as np
np.random.seed(0)

x1= np.random.randint(6,size=6)
x2= np.random.randint(8, size=(3,2))
x3= np.random.randint(12, size=(4,2,4))
!echo 3:
print(x1[3:])
print(x2[3:])
print(x3[3:])
!echo :3
print(x1[:3])
print(x2[:3])
print(x3[:3])
!echo -1:
print(x1[-1:])
print(x2[-1:])
print(x3[-1:])
!echo x1
print(x1)
!echo x3
print(x3)

3:
[3 3 3]
[]
[[[1 3 3 3]
  [7 0 1 9]]]
:3
[4 5 0]
[[7 1]
 [3 5]
 [2 4]]
[[[ 7  6  8  8]
  [10  1  6  7]]

 [[ 7  8  1  5]
  [ 9  8  9  4]]

 [[ 3  0  3  5]
  [ 0  2  3  8]]]
-1:
[3]
[[2 4]]
[[[1 3 3 3]
  [7 0 1 9]]]
x1
[4 5 0 3 3 3]
x3
[[[ 7  6  8  8]
  [10  1  6  7]]

 [[ 7  8  1  5]
  [ 9  8  9  4]]

 [[ 3  0  3  5]
  [ 0  2  3  8]]

 [[ 1  3  3  3]
  [ 7  0  1  9]]]


In [213]:
import numpy as np
np.random.seed(0)
x2= np.random.randint(8, size=(3,2))

print(x2)
print(x2[1,1]) #두번째 행, 두번째 열 원소 조회
print(x2[1,:]) #두번째 행, 모든 열
print(x2[:,1]) #모든 행, 두번째 열
!echo 거꾸로출력
print(x2[::-1,0]) #모든 행 첫 열, 역순
print(x2[::-1,:]) #열 순서는 그대로 두고 행만 역순
print(x2[::-1,::-1]) #행 순서, 열 순서 둘다 역순

[[4 7]
 [5 0]
 [3 3]]
0
[5 0]
[7 0 3]
거꾸로출력
[3 5 4]
[[3 3]
 [5 0]
 [4 7]]
[[3 3]
 [0 5]
 [7 4]]


In [219]:
import numpy as np

x2= np.random.randint(8,size=(3,2))
!echo 원본
print(x2)
print("slice배열 조회")

x2_sub= x2[:2,:2]
print(x2_sub)
print("slice배열 변경.(0~1,0~1)부분만 쪼개서 넣은것")
!echo (0,0)99로 바꿈
x2_sub[0,0]= 99
print(x2_sub)
!echo x2원래것도 (0,0)이 바뀌더라
print(x2)

원본
[[6 7]
 [7 0]
 [2 3]]
slice배열 조회
[[6 7]
 [7 0]]
slice배열 변경.(0~1,0~1)부분만 쪼개서 넣은것
(0,0)99로 바꿈
[[99  7]
 [ 7  0]]
x2원래것도 (0,0)이 바뀌더라
[[99  7]
 [ 7  0]
 [ 2  3]]


#### 조각내서 붙여넣고 값바꾸면 원본도 바뀌니,
### 원본유지하고프면 복사해둬야

In [218]:
import numpy as np
x2= np.random.randint(8,size=(3,2))
!echo 원본
print(x2)
!echo x2 0~1,0~1 부분복사해서 만듦
x2_sub_copy= x2[:2,:2].copy()
print(x2_sub_copy)
!echo 0,0 바꿈
x2_sub_copy[0,0]= 88
print(x2_sub_copy)
!echo 원본
print(x2)

원본
[[1 4]
 [3 0]
 [3 5]]
x2 0~1,0~1 부분복사해서 만듦
[[1 4]
 [3 0]]
0,0 바꿈
[[88  4]
 [ 3  0]]
원본
[[1 4]
 [3 0]
 [3 5]]


In [223]:
import numpy as np
grid= np.arange(1,10)
print(grid)
!echo reshape method
grid= np.arange(1,10).reshape((3,3))
print(grid)

!echo reshape function
x= np.array([1,2,3,4,5,6])
xx= np.reshape(x,(2,3))
print(xx)

[1 2 3 4 5 6 7 8 9]
reshape method
[[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape function
[[1 2 3]
 [4 5 6]]


In [43]:
import matplotlib.pyplot as plt
import numpy as np

x= np.linspace(0, 3*np.pi,500)
plt.plot(x, np.sin(x**2)) # 3**4= 81
plt.title("simple chirp")

Text(0.5,1,'simple chirp')

In [39]:
np.log?

In [17]:
def amazing():
    '''ㄷㄷ?'''
    print('fct name: ',amazing.__name__)
    print('docstring: ',amazing.__doc__)

In [18]:
amazing()

fct name:  amazing
docstring:  ㄷㄷ?


In [2]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [20]:
def sinplot(flip=1):
    x= np.linspace(0,14,100)
    for i in range(1,7):
        plt.plot(x,np.sin(x+i*.5)*(7-i)*flip)

In [45]:
%pwd

'c:\\myjupyter\\test1\\data'

In [43]:
%matplotlib notebook
sinplot()

NameError: name 'sinplot' is not defined

In [52]:
!pwd
%pwd

/c/myjupyter/test1/data


'c:\\myjupyter\\test1\\data'

In [53]:
data_filename= "c:\\myjupyter\\test1\\data\\nyc_data.csv"
print(data_filename)
# fare_filename= "\\data\\nyc_fare_01.csv"
# print(fare_filename)

c:\myjupyter\test1\data\nyc_data.csv


In [4]:
data_filename= "data/nyc_data.csv"
print(data_filename)
# fare_filename= "\\data\\nyc_fare_01.csv"
# print(fare_filename)

data/nyc_data.csv


In [5]:
import pandas as pd
data= pd.read_csv(data_filename)
# fare= pd.read_csv(fare_filename)

In [6]:
data.head(s)

NameError: name 's' is not defined

In [ ]:
data.describe(s)

!pwd

In [9]:
!pwd

/c/myjupyter/test1


In [8]:
!cd ..

In [10]:
%cd ..

C:\myjupyter


In [11]:
!ls

test1
titanic


In [12]:
%cd titanic

C:\myjupyter\titanic
