### 치환과 임의 샘플링
- 180313- p284~ 

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [4]:
np.random.randint(0,5, size= 10)

array([0, 0, 3, 1, 2, 4, 4, 2, 3, 1])

In [6]:
np.random.randint(0,5, size= 5)

array([3, 3, 2, 4, 2])

In [5]:
np.random.permutation(5)

array([1, 0, 3, 4, 2])

In [25]:
set(np.random.randint(0,5, size= 5))

{2, 3, 4}

In [26]:
df= DataFrame(np.arange(5*4).reshape(5,4))
sampler= np.random.permutation(5) #permutation: 순열, 치환
sampler

array([4, 2, 0, 1, 3])

In [27]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

##### 행번호 뒤섞기

In [28]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [29]:
df.take(np.random.permutation(len(df)))

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19
0   0   1   2   3

##### 행번호 뒤섞는데, 전체 중에 3개만

In [30]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11

#### 5개짜리 배열을 해당 요소들로 구성된 10개 짜리 배열로 늘림

In [32]:
bag= np.array([5,7,-1,6,4])
sampler= np.random.randint(0, len(bag), size= 10)
sampler #bag의 index. 근데 크기가 10

array([2, 1, 2, 1, 0, 3, 0, 4, 4, 3])

In [33]:
draws= bag.take(sampler)
draws

array([-1,  7, -1,  7,  5,  6,  5,  4,  4,  6])

### 표시자/더미변수
p285

## 문자열다루기

### 문자열객체 메서드
p289

In [ ]:
val= 'a,b,  guido'