## pandas
고성능 과학계산 컴퓨팅, 데이터분석

In [6]:
# pandas 제작자가 권장하는 import convention
from pandas import Series, DataFrame

In [5]:
import pandas as pd
import numpy as np

### Series
- 객체를 담을 수 있는 1차원 배열같은 자료구조
- numpy 자료형 담을 수 있음
- 고정 길이의 정렬된 dictionary 형태

In [13]:
obj= Series([4,7,-5,3]); obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [10]:
obj.index

RangeIndex(start=0, stop=4, step=1)

#### Series= pd.dictionary
값을 직접 생성해서 만드는 Series는 따로 정렬되지 않음. 입력순서대로 생성

In [12]:
obj2= Series([4,7,-5,3], index= ['d','b','a','c']); obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2['a']

-5

In [16]:
obj2['d']

4

In [18]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [20]:
obj2[obj2> 0]

d    4
b    7
c    3
dtype: int64

In [21]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [23]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

##### 해당 key가 있는지

In [27]:
'b' in obj2

True

In [28]:
'e' in obj2

False

#### set -> Series(셋)
기존 data를 Series로 만든 경우, key값 기준으로 정렬된다

In [33]:
sdata= {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [34]:
obj3= Series(sdata)

In [35]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

#### key는 index= 로 지정된 것만 데려옴
Series(데이터1, index= 데이터2)

In [42]:
#California 없고, Utah 있음
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [36]:
states= ['California', 'Ohio', 'Oregon', 'Texas']

In [38]:
obj4= Series(sdata, index= states); obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

#### null? (NaN)
누락 데이터 보기

In [39]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [40]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [43]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

#### key가 한쪽에만 있는 경우, 연산 결과

In [45]:
#유타ㅇ, 캘리포니아X
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [47]:
#유타X, 캘리포니아ㅇ
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [50]:
#캘리포니아 null ㅇㅇ
#유타. value가 있지만, key가 한쪽에만 있기에 null
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

#### .name
Series 객체, Series 색인에 있는 속성

In [51]:
obj4.name

In [52]:
obj4.name= 'population'
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [54]:
obj4.index.name= 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## 예제
1. 5x4 배열. .txt 저장
2. dataframe 생성& 칼럼명 지정

In [11]:
import pandas as pd
import numpy as np

#### 1

In [59]:
a= np.zeros((3,5)); a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [63]:
!dir

 E 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2468-0A05

 E:\github\dataAnal_py_basic\popularPkg 디렉터리

2018-03-07  오후 12:43    <DIR>          .
2018-03-07  오후 12:43    <DIR>          ..
2018-03-07  오후 12:32    <DIR>          .ipynb_checkpoints
2018-03-02  오전 09:28            22,132 crawling.ipynb
2018-03-07  오전 11:09    <DIR>          data
2018-02-23  오전 09:42               269 handbook.py
2018-03-07  오전 11:39           441,272 markdown.ipynb
2018-03-06  오후 05:08            43,946 numpy_array_index_ix__tranpose_swapaxes.ipynb
2018-03-06  오후 05:09            67,324 numpy_array_slice_index.ipynb
2018-03-07  오전 11:21             6,812 numpy_sort_set_file.ipynb
2018-03-06  오후 06:56            17,927 numpy_where_max_sum_with_axis.ipynb
2018-02-28  오전 09:55            93,684 pandas1.ipynb
2018-03-07  오후 12:43            13,992 pandas_Series.ipynb
               9개 파일             707,358 바이트
               4개 디렉터리  226,312,949,760 바이트 남음


In [67]:
!start .

In [68]:
np.savetxt('./data/savetest2', a, fmt="%d")

#### 2

In [7]:
from pandas import Series, DataFrame

In [1]:
import numpy as np

In [2]:
%cd data
%ls
%cd ..

E:\github\dataAnal_py_basic\popularPkg\data
 E 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2468-0A05

 E:\github\dataAnal_py_basic\popularPkg\data 디렉터리

2018-03-07  오후 12:46    <DIR>          .
2018-03-07  오후 12:46    <DIR>          ..
2018-03-07  오후 12:46                35 ex_df.txt
2018-03-07  오전 11:09                20 ex_text.txt
2018-03-07  오전 11:05                20 save_test2
2018-03-07  오후 12:45                30 savetest2
               4개 파일                 105 바이트
               2개 디렉터리  226,312,802,304 바이트 남음
E:\github\dataAnal_py_basic\popularPkg


In [3]:
ex_df= np.loadtxt('./data/ex_df.txt')

In [4]:
ex_df

array([[   1.,  500.,    5.],
       [   2.,  200.,    2.],
       [   3.,  200.,    7.],
       [   4.,   50.,    9.]])

In [5]:
# ex_DF= DataFrame(ex_df); ex_DF

In [8]:
ex_DF= DataFrame(ex_df, columns=['name', 'price', 'qty']); ex_DF

name  price  qty
0   1.0  500.0  5.0
1   2.0  200.0  2.0
2   3.0  200.0  7.0
3   4.0   50.0  9.0

In [9]:
ex_DF.columns

Index(['name', 'price', 'qty'], dtype='object')

In [11]:
#행번호 변경
ex_DF.index= np.arange(1,5,1) # [1,5)

In [12]:
ex_DF

name  price  qty
1   1.0  500.0  5.0
2   2.0  200.0  2.0
3   3.0  200.0  7.0
4   4.0   50.0  9.0

In [14]:
data={'state': ['Ohio','Ohio','Ohio','Nevada','Nevada'],
      'year': [2000,2001,2002,2001,2002],
      'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
     }
frame= DataFrame(data)

In [15]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [16]:
DataFrame(data, columns= ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [18]:
frame2= DataFrame(data, columns= ['year', 'state', 'pop','debt']
                  , index= ['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [19]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

### 칼럼 접근

In [20]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [21]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

### 로우 접근
.ix 비추
- .iloc 정수
- .loc 레이블

In [23]:
#is deprecated. loc나 iloc 권장
frame2.ix['two']

C:\Users\kitcoop\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [24]:
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [25]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [26]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: debt, dtype: object

In [27]:
frame2['debt']= 16.5

In [28]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [29]:
frame2['debt']= np.arange(5); frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [30]:
frame2['debt']= np.arange(5.); frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

### 예제
1. .
2. .
3. 예제2 DataFrame에서 행이름 과일명으로
4. name칼럼뒤에 code 칼럼. 값수정c00#
5. 사과오렌지,price qty 만
6. qty가 4보다큰 과일은 몇 개?

In [32]:
ex_1= np.loadtxt('./data/ex_df.txt')
df= DataFrame(ex_1, columns=['name', 'price', 'qty']); df

name  price  qty
0   1.0  500.0  5.0
1   2.0  200.0  2.0
2   3.0  200.0  7.0
3   4.0   50.0  9.0

#### 3

In [34]:
fruits= ['apple','banana','orange','peach']
df.index= fruits

In [35]:
df

name  price  qty
apple    1.0  500.0  5.0
banana   2.0  200.0  2.0
orange   3.0  200.0  7.0
peach    4.0   50.0  9.0

#### 4

In [37]:
#응 안되
# df.columns=['name', 'code', 'price', 'qty']; df

#### code_contents 세련되게 해보자

In [77]:
code_contents= ['c00'+str(i) for i in range(1,5,1)]; code_contents

['c001', 'c002', 'c003', 'c004']

In [112]:
code_contents= ['c00%d'%i for i in range(1,5,1)]; code_contents

['c001', 'c002', 'c003', 'c004']

#### loc 값도 세련되게 얻어보자

In [105]:
df.columns

Index(['name', 'price', 'qty'], dtype='object')

In [109]:
loc_name= list(df.columns).index('name'); loc_name

0

In [111]:
loc_name= df.columns.get_loc("name"); loc_name

0

In [110]:
df.insert(loc=loc_name+1, column= 'code', value= code_contents)
df

name  code  price  qty
apple    1.0  c001  500.0  5.0
banana   2.0  c002  200.0  2.0
orange   3.0  c003  200.0  7.0
peach    4.0  c004   50.0  9.0

#### 혹은, DataFrame을 새로이 만들어서

In [69]:
# 1번만 실행해야
# del df['code']

In [70]:
df

name  price  qty
apple    1.0  500.0  5.0
banana   2.0  200.0  2.0
orange   3.0  200.0  7.0
peach    4.0   50.0  9.0

In [71]:
df2= DataFrame(df, columns= ['name', 'code', 'price', 'qty']); df2

name  code  price  qty
apple    1.0   NaN  500.0  5.0
banana   2.0   NaN  200.0  2.0
orange   3.0   NaN  200.0  7.0
peach    4.0   NaN   50.0  9.0

In [72]:
df2['code']= code_contents
df2

name  code  price  qty
apple    1.0  c001  500.0  5.0
banana   2.0  c002  200.0  2.0
orange   3.0  c003  200.0  7.0
peach    4.0  c004   50.0  9.0

#### 5
- 1개면 df['name']
- 2개 이상이면 df[['name','code']]

In [55]:
df[['name','code']].loc[['banana','orange']]

name  code
banana   2.0  c002
orange   3.0  c003

#### 6

In [61]:
df['qty']>=4

apple      True
banana    False
orange     True
peach      True
Name: qty, dtype: bool

In [60]:
(df['qty']>=4).sum()

3

In [93]:
print(frame2.index)
print(frame2.columns)
print(frame2.shape)
print(type(frame2))
# frame2?
print(len(frame2.columns))
print(len(frame2.index))
print(len(frame2)) # row length

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')
Index(['year', 'state', 'pop', 'debt'], dtype='object')
(5, 4)
<class 'pandas.core.frame.DataFrame'>
4
5
5


In [96]:
val= Series([-1.2, -1.5, -.7], index= ['two','four','five'])
val

two    -1.2
four   -1.5
five   -0.7
dtype: float64

In [97]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [101]:
del frame2['debt']
frame2

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9

In [98]:
frame2['debt']= 

one      0.0
two      1.0
three    2.0
four     3.0
five     4.0
Name: debt, dtype: float64